### ISSUE TITLE
I am now going through the pre-training part, but the error did not find the data set named acid, the specific error message is here, please tell me where I should find this data set.

### ISSUE THREAD

**Issue by hmbbsbb** [dcharatan/flowmap#41]
python3 -m flowmap.pretrain
rm: 无法删除 'outputs/local': 没有那个文件或目录
Using cache found in /home/zmm/.cache/torch/hub/intel-isl_MiDaS_master
Loading weights:  None
Using cache found in /home/zmm/.cache/torch/hub/rwightman_gen-efficientnet-pytorch_master
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 4080 SUPER') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name           | Type                | Params
-------------------------------------------------------
0 | flow_predictor | FlowPredictorGMFlow | 0     
1 | model          | Model               | 21.3 M
-------------------------------------------------------
21.3 M    Trainable params
0         Non-trainable params
21.3 M    Total params
85.382    Total estimated model params size (MB)
Loading CO3D sequences: 100%|███████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 15.71it/s]
Error executing job with overrides: []██████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 16.40it/s]
Traceback (most recent call last):
  File "/home/zmm/anaconda3/envs/flowmap/flowmap/flowmap/pretrain.py", line 66, in pretrain
    trainer.fit(
  File "/home/zmm/anaconda3/envs/flowmap/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/home/zmm/anaconda3/envs/flowmap/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zmm/anaconda3/envs/flowmap/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/zmm/anaconda3/envs/flowmap/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 987, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/home/zmm/anaconda3/envs/flowmap/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1031, in _run_stage
    self._run_sanity_check()
  File "/home/zmm/anaconda3/envs/flowmap/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1060, in _run_sanity_check
    val_loop.run()
  File "/home/zmm/anaconda3/envs/flowmap/lib/python3.11/site-packages/lightning/pytorch/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zmm/anaconda3/envs/flowmap/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 110, in run
    self.setup_data()
  File "/home/zmm/anaconda3/envs/flowmap/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 166, in setup_data
    dataloaders = _request_dataloader(source)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zmm/anaconda3/envs/flowmap/lib/python3.11/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 342, in _request_dataloader
    return data_source.dataloader()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zmm/anaconda3/envs/flowmap/lib/python3.11/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 309, in dataloader
    return call._call_lightning_datamodule_hook(self.instance.trainer, self.name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zmm/anaconda3/envs/flowmap/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 179, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/zmm/anaconda3/envs/flowmap/flowmap/flowmap/dataset/data_module_pretrain.py", line 76, in val_dataloader
    dataset = get_dataset(self.dataset_cfgs, "val", self.frame_sampler_cfg)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zmm/anaconda3/envs/flowmap/lib/python3.11/site-packages/jaxtyping/_decorator.py", line 450, in wrapped_fn
    out = fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/zmm/anaconda3/envs/flowmap/flowmap/flowmap/dataset/__init__.py", line 34, in get_dataset
    datasets = [
               ^
  File "/home/zmm/anaconda3/envs/flowmap/flowmap/flowmap/dataset/__init__.py", line 35, in <listcomp>
    DATASETS[cfg.name](cfg, stage, frame_sampler) for cfg in dataset_cfgs
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zmm/anaconda3/envs/flowmap/lib/python3.11/site-packages/jaxtyping/_decorator.py", line 450, in wrapped_fn
    out = fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/zmm/anaconda3/envs/flowmap/flowmap/flowmap/dataset/dataset_re10k.py", line 48, in __init__
    [path for path in root.iterdir() if path.suffix == ".torch"]
  File "/home/zmm/anaconda3/envs/flowmap/flowmap/flowmap/dataset/dataset_re10k.py", line 48, in <listcomp>
    [path for path in root.iterdir() if path.suffix == ".torch"]
  File "/home/zmm/anaconda3/envs/flowmap/lib/python3.11/pathlib.py", line 931, in iterdir
    for name in os.listdir(self):
                ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/acid/test'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by dcharatan** [comment]
This is a preprocessed ACID dataset (the same one used to train pixelSplat). There's a note about it [here](https://github.com/dcharatan/pixelsplat?tab=readme-ov-file#acquiring-datasets). Email me at charatan@mit.edu if you want the link.
